name: '{why not}.io'
markdown: redcarpet
highlighter: 'pygments'
permalink: /:categories/:title/
exclude: ["Gemfile*", "Guardfile", "Rakefile"]
excerpt_seperator: <!--more-->

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      type: "post"

gems:
  - jekyll-redirect-from
  - jekyll-sitemap
